# Generated by Django 4.2.5 on 2024-03-15 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='attendance',
            field=models.CharField(default=90, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='marks',
            field=models.CharField(default=85, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=12378, max_length=50),
            preserve_default=False,
        ),
    ]
